"""Utility functions for exporting documents to .txt, .docx, and .pdf."""

import io
from fpdf import FPDF
from docx import Document
from docx.shared import Pt, Inches


def to_txt(content: str) -> bytes:
    return content.encode("utf-8")


def to_docx(content: str, title: str = "Legal Document") -> bytes:
    doc = Document()

    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    # Title
    heading = doc.add_heading(title, level=0)

    # Body — split by lines, preserve blank lines
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped:
            doc.add_paragraph("")
            continue

        # Detect headings: lines in ALL CAPS or starting with digit+dot
        is_heading = (
            stripped.isupper()
            or (stripped[:3].rstrip(".").isdigit())
        ) and len(stripped) < 120

        if is_heading:
            p = doc.add_paragraph()
            run = p.add_run(stripped)
            run.bold = True
            run.font.size = Pt(12)
        else:
            doc.add_paragraph(stripped)

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()


class _PDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 6, "Generated by LegalEase", align="R")
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 8, f"Page {self.page_no()}", align="C")


def to_pdf(content: str, title: str = "Legal Document") -> bytes:
    pdf = _PDF(format="A4")
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(20, 20, 20)
    pdf.multi_cell(0, 9, title)
    pdf.ln(4)

    # Body
    pdf.set_font("Helvetica", "", 10.5)
    pdf.set_text_color(30, 30, 30)

    for raw_line in content.splitlines():
        line = raw_line.rstrip()
        if not line.strip():
            pdf.ln(4)
            continue

        stripped = line.strip()
        is_heading = (
            stripped.isupper()
            or (stripped[:3].rstrip(".").isdigit())
        ) and len(stripped) < 120

        if is_heading:
            pdf.set_font("Helvetica", "B", 11.5)
            pdf.multi_cell(0, 7, stripped)
            pdf.set_font("Helvetica", "", 10.5)
        else:
            # Replace unsupported unicode chars with ascii
            safe = stripped.encode("latin-1", "replace").decode("latin-1")
            pdf.multi_cell(0, 6, safe)

    out = pdf.output(dest="S")
    if isinstance(out, str):
        return out.encode("latin-1")
    return bytes(out)